[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  functions = "functions"

[[redirects]]
  from = "/api/v1/auth/*"
  to = "/.netlify/functions/auth"
  status = 200

[[redirects]]
  from = "/api/v1/staff/*"
  to = "/.netlify/functions/staff"
  status = 200