// Staff Form Strucutre
exports.generateEmployee = function (selectedEmployee) {
  if (!selectedEmployee) {
    selectedEmployee = {
      "initials": null,
      "first_name": null,
      "middle_name": null,
      "last_name": null,
      "full_name": null,
      "email": null,
      "dob": null,
      "marital_status": 0,
      "gender": 0,
      "title": 0,
      "blood_group": null,
      "place_of_birth": "",
      "nic": "",
      "passport_number": "",
      "passport_expiry": "",
      "driving_license_number": "",
      "religion": "",
      "nationality": "",
      "race": "",
      "employee_number": null,
      "epf_number": null,
      "etf_number": null,
      "attendance_id": null,
      "previous_epf_number": null,
      "designation": null,
      "joined_designation": null,
      "reporting_person": null,
      "reporting_designation": null,
      "location": "Office",
      "job_description": null,
      "cost_center_code": null,
      "functional_reporting_person": null,
      "basic_salary": null,
      "housing_amount": null,
      "budgetary_relief_allowance": null,
      "method_joined": null,
      "pension_scheme": null,
      "participated_to_induction": null,
      "shift": "General Shift",
      "status": null,
      "date_of_appointment": "2025-01-01",
      "employment_type": "Permanent",
      "prior_notice_period": 0,
      "confirmation_due_on": null,
      "overtime": 0,
      "date_of_retirement": "2030-01-01",
      "building": null,
      "street": null,
      "city": null,
      "postal_code": null,
      "district": null,
      "country": null,
      "office_phone": null,
      "extension_number": null,
      "office_email": null,
      "personal_mobile": null,
      "personal_email": null,
      "province": null,
      "electorate": null,
      "polling_division": null,
      "distance_to_workplace": null,
      "travel_mode": null,
      "ec1_name": null,
      "ec1_relationship": null,
      "ec1_mobile_number": null,
      "ec1_building": null,
      "ec1_street": null,
      "ec1_city": null,
      "ec1_postal_code": null,
      "ec1_district": null,
      "ec1_country": null,
      "ec1_telephone": null,
      "ec2_name": null,
      "ec2_relationship": null,
      "ec2_mobile_number": null,
      "ec2_building": null,
      "ec2_street": null,
      "ec2_city": null,
      "ec2_postal_code": null,
      "ec2_district": null,
      "ec2_country": null,
      "ec2_telephone": null
    };
  }
  selectedEmployee["deleted"] = false;
  return selectedEmployee;
};